/* Automatically generated by './build/bin/build-entry.js' */

import Button from '../src/components/button/index.js';
import ButtonGroup from '../src/components/button-group/index.js';
import Icon from '../src/components/icon/index.js';
import Input from '../src/components/input/index.js';
import Radio from '../src/components/radio/index.js';
import RadioGroup from '../src/components/radio-group/index.js';
import Cascader from '../src/components/cascader/index.js';

const components = [
	Button,
	ButtonGroup,
	Icon,
	Input,
	Radio,
	RadioGroup,
	Cascader,
];

const install = function(Vue, opts = {}) {
	components.forEach(component => {
		Vue.component(component.name, component);
	});

	Vue.prototype.$ELEMENT = {
		size: opts.size || '',
		zIndex: opts.zIndex || 2000
	};
};

if (typeof window !== 'undefined' && window.Vue) {
	install(window.Vue);
}

export default {
	version: '0.0.3',
	install,
	Button,
	ButtonGroup,
	Icon,
	Input,
	Radio,
	RadioGroup,
	Cascader
};
